### ISSUE TITLE
Configuring luarocks fails in installer page

### ISSUE THREAD

**Issue by NStefan002** [nvim-neorocks/rocks.nvim#123]
Hi! I like the idea of this project and wanted to try it but run into some issues. It's probably some stupid mistake on my part so I apologize in advance. 

So, I used the command given in README (`:source ...`), and the installer page opened up, I didn't change the default values, clicked OK, and then I got the following messages.
```
Downloading luarocks...
Configuring luarocks...
Configuring luarocks failed:
```

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting.
Is that the only output?

It's recently come to our attention that some plugins can interfere with the installer script.

Instead of just `:source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua`, you can try `nvim -u NORC  +"source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"`.

This will start neovim without loading any user settings and will then run the source command.

**Comment by NStefan002** [comment]
> Is that the only output?

Yes. 

> It's recently come to our attention that some plugins can interfere with the installer script.

Oh, I forgot to mention. I was running the latest neovim nightly without any configuration (removed `~/.config/nvim` and `~/.local/share/nvim/` directories). I'm on Ubuntu 22.04 if that matters, and I have all of the required tools (from README) installed (git, curl, etc.)

> `nvim -u NORC  +"source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"`

I ran this for good measure, but the result is the same.

**Comment by mrcjkb** [comment]
🤔 based on the error message, it fails when trying to reset the luarocks clone to the revision `d81020338c99ff4116431ee496a7db516eb91f00`, which we do because of a bug in newer versions of luarocks.
We print `stderr` when it fails, but maybe git outputs the error to `stdout`. We should probably print both...

I wonder why it's failing for you.
Could you please try cloning [luarocks](https://github.com/luarocks/luarocks.git) and running `git reset --hard d81020338c99ff4116431ee496a7db516eb91f00` within your clone? (I would do it myself, but I'm not near my laptop right now).

**Comment by NStefan002** [comment]
Of course, no problem. Just to be clear, I should clone luarocks, reset it to the given commit, and run `./configure && make && sudo make install`?

**Comment by mrcjkb** [comment]
Oh yeah, it could be the `configure` that is failing. Good call.

We run 

```
configure --prefix=<install_path> --lua-version=5.1 --force-config
```

Where `<install_path>` is the path set in the installer UI.

**Comment by NStefan002** [comment]
Ok, I installed everything manually, and it works. Steps I did if it helps:
1. `git clone git@github.com:luarocks/luarocks.git`
2. `cd luarocks`
3. `./configure && make && sudo make install`
4. `sudo apt install -y lua5.1 liblua5.1-dev`
5. in the installer page set `Should rocks.nvim set up Luarocks?` to `false`
6. press < OK >

**Comment by mrcjkb** [comment]
Glad it worked out.
I'll update the installer script to also print `stdout` if something fails.

By the way, on Ubuntu, you should be able to `apt install luarocks`, too.
Not sure if it's configured to set the lua version to 5.1 though (which is necessary for neovim plugins).
If not, you can also run `luarocks config lua_version 5.1`.

**Comment by NStefan002** [comment]
> If not, you can also run `luarocks config lua_version 5.1`
Thanks for that.

Closing this.
