### ISSUE TITLE
`luarocks` failed to install `toml-edit`

### ISSUE THREAD

**Issue by jinzhongjia** [nvim-neorocks/rocks.nvim#22]
`luarocks` will fail to install toml-edit. 
Try to install it through the command line, the following prompt appears:
![image](https://github.com/nvim-neorocks/rocks.nvim/assets/41784264/18763812-1d10-49fe-af72-8da5f262cd84)

Neovim version: `nightly`

Try to run `luarocks config` , it outpus:

5.4 outputs: https://gist.github.com/jinzhongjia/0b1acc55bebd5a56a7e17f9a9df6f53e
with `--lua-version=5.1` outputs: https://gist.github.com/jinzhongjia/bcfbda053813f8e2e8e3236e9b811cf8

**Comment by jinzhongjia** [comment]
Acorrding to [this](https://github.com/nvim-neorocks/rocks.nvim/issues/19#issuecomment-1787030570), masybe it is a bug of `luarocks`

**Comment by mrcjkb** [comment]
We just encountered [the same error in our `luarocks` CD workflow](https://github.com/nvim-neorocks/rocks.nvim/actions/runs/6935248096/job/18865141775#step:4:612).

The workaround was to have either a local or global installation of `luarocks-build-rust-mlua` (`luarocks install --local luarocks-build-rust-mlua`).

It appears that luarocks can't find it if it is installed using `--tree <some-path>` (perhaps another luarocks bug?).

For us, I think the best solutions will be

1. Provide `toml-edit` as a binary rock, which we can install using `--server <manifest-uri>`.
1. An upstream fix.

**Comment by NTBBloodbath** [comment]
I will close this issue because we now have binary rocks (aka bundled dependencies) in another public repository that rocks.nvim uses to install its dependencies and it is no longer necessary to compile anything.

Please reopen this issue if for some reason the problem still persists using the rocks.nvim installer (although I'm pretty sure you won't have to face it again!).
