### ISSUE TITLE
[Feature] sync individual rocks

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#421]

**Comment by vhyrro** [comment]
I'd thought of this, but came to the conclusion that it was a weird thing to provide (since syncing involves syncing the entire filesystem state with the rocks.toml file, not an individual rock).

Although, given that `rocks-git` updates plugins on sync, that does make me wonder - is it our fault for making users think that syncing also updates? If rocks-git only synced and never updated (and left that to `:Rocks update` instead), is this then still a desired feature? Happy to hear some thoughts :p

**Comment by mrcjkb** [comment]
> Although, given that `rocks-git` updates plugins on sync, that does make me wonder

`rocks-git` only updates plugins on sync if the `rev` is not pinned.
I think the issue is that `sync` is currently painfully slow with lots of plugins. Once that is solved, I don't think this will be necessary.
So let's close this for now and revisit it again if needed.
